import{S as d,i as l}from"./assets/vendor-0fc460d7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();function p(s){const o="45157034-b6e4e263cfc131778ce7a37cc",n="https://pixabay.com/api/1111",t=new URLSearchParams({key:o,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${n}?${t}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).catch(e=>{console.log(e)})}const c=document.querySelector(".gallery");function h(s){let o=s.hits.map(t=>`<li>
        <a class="gallery-link" href=${t.largeImageURL}>
          <img src="${t.webformatURL}" alt="${t.tags}" width=360 height=200>
          <div class="gallery-text">
            <p><span>Likes</span>${t.likes}</p>
            <p><span>Views</span>${t.views}</p>
            <p><span>Comments</span>${t.comments}</p>
            <p><span>Downloads</span>${t.downloads}</p>
          </div>
        </a>
      </li>`).join("");c.insertAdjacentHTML("beforeend",o),new d(".gallery a",{captionDelay:250,captionPosition:"bottom",captionsData:"alt"}).refresh()}function m(s){c.innerHTML="",alert("Ooops, something went wrong!")}const f=document.querySelector(".gallery"),u=document.querySelector(".form"),y=document.querySelector(".input"),i=document.querySelector(".loader");u.addEventListener("submit",g);function g(s){s.preventDefault(),f.innerHTML="",i.classList.remove("visually-hidden");const o=y.value.trim();if(o===""){i.classList.add("visually-hidden"),l.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"This field can not be empty! Please, write your request!"});return}p(o).then(n=>{i.classList.add("visually-hidden"),n.hits.length===0?l.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}):(i.classList.add("visually-hidden"),h(n))}).catch(m),u.reset()}
//# sourceMappingURL=commonHelpers.js.map
