import{S as c,i as u}from"./assets/vendor-0fc460d7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function d(n){const o="45157034-b6e4e263cfc131778ce7a37cc",s="https://pixabay.com/api/",t=new URLSearchParams({key:o,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${s}?${t}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()}).catch(e=>{console.log(e)})}const p=document.querySelector(".gallery");function f(n){let o=n.hits.map(t=>`<li>
        <a class="gallery-link" href=${t.largeImageURL}>
          <img src="${t.webformatURL}" alt="${t.tags}" width=360 height=200>
          <div class="gallery-text">
            <p><span>Likes</span>${t.likes}</p>
            <p><span>Views</span>${t.views}</p>
            <p><span>Comments</span>${t.comments}</p>
            <p><span>Downloads</span>${t.downloads}</p>
          </div>
        </a>
      </li>`).join("");p.insertAdjacentHTML("beforeend",o),new c(".gallery a",{captionDelay:250,captionPosition:"bottom",captionsData:"alt"}).refresh()}const h=document.querySelector(".gallery"),l=document.querySelector(".form"),m=document.querySelector(".input"),i=document.querySelector(".loader");l.addEventListener("submit",y);function y(n){n.preventDefault(),h.innerHTML="",i.classList.remove("visually-hidden");const o=m.value.trim();if(o===""){i.classList.add("visually-hidden");return}d(o).then(s=>{i.classList.add("visually-hidden"),s.hits.length===0?u.error({maxWidth:"370px",position:"topRight",messageColor:"white",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}):(i.classList.add("visually-hidden"),f(s))}).catch(s=>{console.error(s)}),l.reset()}
//# sourceMappingURL=commonHelpers.js.map
